module.exports = async (req, res) => {
  // Set CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization, x-visma-client-id, x-visma-client-secret, x-visma-access-token');
  res.setHeader('Access-Control-Allow-Credentials', 'true');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  // Handle GET - List all presets
  if (req.method === 'GET') {
    try {
      // Return default presets
      const presets = [
        {
          id: 1,
          code: 'OK',
          name: 'Norsk import (+mva)',
          article_name: 'Norsk import (+mva)',
          unit_price_cents: 41400, // 414 NOK
          currency: 'NOK',
          vat_code: '25'
        }
      ];

      return res.json(presets);
    } catch (error) {
      console.error('Error loading presets:', error);
      return res.status(500).json({ error: 'Failed to load presets' });
    }
  }

  // Handle POST - Create new preset
  if (req.method === 'POST') {
    try {
      const { code, name, unit_price_cents, currency, vat_code, article_name } = req.body;

      if (!code || !name || !unit_price_cents) {
        return res.status(400).json({ error: 'Missing required fields: code, name, unit_price_cents' });
      }

      // Note: In Vercel serverless functions, we can't persist in-memory data between requests.
      // This implementation returns the new preset but it won't persist across requests.
      // For persistent storage, you would need to implement a database connection.

      const newPreset = {
        id: 2, // In a real implementation, this would be generated by the database
        code,
        name,
        unit_price_cents: parseInt(unit_price_cents),
        currency: currency || 'NOK',
        vat_code: vat_code || '25',
        article_name: article_name || name
      };

      console.log(`✅ Preset creation requested:`, newPreset);

      return res.json(newPreset);
    } catch (error) {
      console.error('Error creating preset:', error);
      return res.status(500).json({ error: 'Failed to create preset', details: error.message });
    }
  }

  return res.status(405).json({ error: 'Method not allowed' });
};
